// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaOKws8vE0CI315fsv8XxdvheXYMMP6o0',
    appId: '1:879444927653:web:6e52abc638d1f53f68594c',
    messagingSenderId: '879444927653',
    projectId: 'authenticationappfirebase',
    authDomain: 'authenticationappfirebase.firebaseapp.com',
    storageBucket: 'authenticationappfirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBueSItTpXZ5NnnYsH0uN8MJsVNccXDMpA',
    appId: '1:879444927653:android:2b921d2eeb1f471368594c',
    messagingSenderId: '879444927653',
    projectId: 'authenticationappfirebase',
    storageBucket: 'authenticationappfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOE037MesHaOMJSqdR61kTT5y_RWNgUYo',
    appId: '1:879444927653:ios:b13262f39c1eee4d68594c',
    messagingSenderId: '879444927653',
    projectId: 'authenticationappfirebase',
    storageBucket: 'authenticationappfirebase.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOE037MesHaOMJSqdR61kTT5y_RWNgUYo',
    appId: '1:879444927653:ios:c705682161072e2c68594c',
    messagingSenderId: '879444927653',
    projectId: 'authenticationappfirebase',
    storageBucket: 'authenticationappfirebase.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
